### ISSUE TITLE
Running LAVA on a Windows machine using docker

### ISSUE THREAD

**Issue by Stalinho** [panda-re/lava#56]
How do I go about injecting bugs into a program by running LAVA from a docker container on a windows host machine? I have managed to create a docker image from the provided docker files. However, the docker container created by the image isn't starting.

**Comment by moyix** [comment]
Hmm, I don't think we've ever tried to run this on anything but Linux. Some parts of LAVA are meant to run outside of Docker (although @HighW4y2H3ll recently proposed https://github.com/panda-re/lava/pull/54 which moves most of those into Docker, it still needs a postgresql server running on the host) and I would not expect them to work on a Windows system.
