### ISSUE TITLE
Toy program details

### ISSUE THREAD

**Issue by smeet2804** [panda-re/lava#75]
It would be great if you can provide more details about toy program provided in the readme file. I would like to know where i can find original source code for it and lava generated buggy source code.

**Comment by AndrewQuijano** [comment]
This should be it

https://github.com/moyix/toy/blob/main/toy.c

**Comment by smeet2804** [comment]
Hi Andrew, could you please let me know where can I get the buggy source code of toy.c after running lava on it? Thanks!
